#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@caldera.de>
# Rewritten to use lists instead of if-statements.
#

include $(TOPDIR)/make/common_header.mk

obj-y := $(APP)/ ../libs/

include $(TOPDIR)/make/common_footer.mk
