
#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@caldera.de>
# Rewritten to use lists instead of if-statements.
#

include $(TOPDIR)/make/common_header.mk

obj-y	+= osa_buf.c
#obj-y	+= osa_cmem.c
obj-y	+= osa_file.c
obj-y	+= osa_flg.c
obj-y	+= osa_ipc.c
obj-y	+= osa_mbx.c
obj-y	+= osa_msgq.c
obj-y	+= osa_mutex.c
obj-y	+= osa_prf.c
obj-y	+= osa_que.c
obj-y	+= osa_sem.c
obj-y	+= osa_thr.c
obj-y	+= osa_tsk.c
obj-y	+= osa.c

TARGET=lib

include $(TOPDIR)/make/common_footer.mk
