# (c) Texas Instruments 

include $(FILE_OBJS)

$(BUILD_OUTPUT_DIR)/lib$(CUR_DIR_NAME).a:$(RAM_OBJS)
	@if [ -n "$(RAM_OBJS)" ] ; then \
		rm -f $@; \
		echo "  [AR] $(subst ${TOPDIR}/,,$@)"; \
		$(AR) rcs $@ $(RAM_OBJS); \
	fi

$(BUILD_OUTPUT_DIR)/lib$(CUR_DIR_NAME).o:$(RAM_OBJS)
	$(Q)$(LD) -r -o $@ $(RAM_OBJS)

$(BINARY):$(RAM_OBJS) $(BUILD_OUTPUT_DIR)/.build
	@echo $(BUILD_OUTPUT_DIR)
	@echo "  [LD] $(subst ${TOPDIR}/,,$@)"
	$(Q)$(CC) -lstdc++ -o $@ $(RAM_OBJS) \
			$(LDFLAGS)	
	